model = "E2-TTS"
ref_audio = "mommy-ref.wav"
ref_text = "Everything else is not evaluated in parallel. Here are some examples to help. Assume we have some functions, foo and bar. Then each of the following lines will be stating whether foo and bar."
gen_text = "hi. this is a test. potato."
gen_file = ""
remove_silence = true
output_dir = "output"
output_file = "mommy.wav"
