model = "F5-TTS"
ref_audio = "infer/examples/basic/basic_ref_en.wav"
ref_text = "Some call me nature, others call me mother nature."
gen_text = "hi"
gen_file = ""
remove_silence = false
output_dir = "static/audio"
output_file = "generated_audio.wav"
