model = "F5-TTS"
ref_audio = "infer/examples/basic/basic_ref_en.wav"
ref_text = "Some call me nature, others call me mother nature."
gen_text = "hi. this is a test"
gen_file = ""
remove_silence = false
output_dir = "tests"
output_file = "babygirl.wav"
